---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.kannon92
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - cache.kannon92
  resources:
  - kueueoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.kannon92
  resources:
  - kueueoperators/finalizers
  verbs:
  - update
- apiGroups:
  - cache.kannon92
  resources:
  - kueueoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
